"""add_company_tables_and_farmer_columns

Revision ID: 2d31842ea20d
Revises: 87b0630bfcf7
Create Date: 2026-08-29 11:31:32.499859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d31842ea20d'
down_revision: Union[str, Sequence[str], None] = '87b0630bfcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('authorized_person_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='companyapprovalstatus'), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_procurement_companies_id'), 'procurement_companies', ['id'], unique=False)
    op.create_table('company_crop_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('maximum_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('procurement_rate', sa.Float(), nullable=True),
    sa.Column('procured_quantity', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['procurement_companies.id'], ),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_crop_requirements_id'), 'company_crop_requirements', ['id'], unique=False)
    op.add_column('farmers', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('farmers', sa.Column('mandal', sa.String(length=100), nullable=True))
    op.add_column('farmers', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('farmers', sa.Column('land_area', sa.Float(), nullable=True))
    op.add_column('farmers', sa.Column('primary_crops', sa.String(length=255), nullable=True))
    op.add_column('farmers', sa.Column('other_crops', sa.String(length=255), nullable=True))
    op.add_column('farmers', sa.Column('preferred_centre_id', sa.Integer(), nullable=True))
    # NOTE: Skipping create_foreign_key for farmers.preferred_centre_id on SQLite.
    # SQLite does not support ALTER to add constraints. The column is still added above.
    # On PostgreSQL, uncomment: op.create_foreign_key(None, 'farmers', 'procurement_centres', ['preferred_centre_id'], ['id'])
    # NOTE: Skipping alter_column on users.role — SQLite ignores VARCHAR length
    # and the existing data already stores enum values as strings correctly.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Skipping alter_column on users.role (see upgrade notes)
    # NOTE: Skipping drop_constraint on SQLite (was never created)
    # On PostgreSQL, uncomment: op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.drop_column('farmers', 'preferred_centre_id')
    op.drop_column('farmers', 'other_crops')
    op.drop_column('farmers', 'primary_crops')
    op.drop_column('farmers', 'land_area')
    op.drop_column('farmers', 'pincode')
    op.drop_column('farmers', 'mandal')
    op.drop_column('farmers', 'email')
    op.drop_index(op.f('ix_company_crop_requirements_id'), table_name='company_crop_requirements')
    op.drop_table('company_crop_requirements')
    op.drop_index(op.f('ix_procurement_companies_id'), table_name='procurement_companies')
    op.drop_table('procurement_companies')
    # ### end Alembic commands ###
