"""Add email verification fields

Revision ID: ada0dbb8ba3c
Revises: de987fa3527b
Create Date: 2026-08-29 23:24:12.915038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada0dbb8ba3c'
down_revision: Union[str, Sequence[str], None] = 'de987fa3527b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_otp_requests_email'), 'otp_requests', ['email'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_otp_requests_email'), table_name='otp_requests')
    op.drop_column('otp_requests', 'email')
    # ### end Alembic commands ###
