"""add_operator_approved_status

Revision ID: c1a9548d19c2
Revises: ada0dbb8ba3c
Create Date: 2026-08-30 15:33:09.349980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a9548d19c2'
down_revision: Union[str, Sequence[str], None] = 'ada0dbb8ba3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'is_approved')
    # ### end Alembic commands ###
