"""Add advanced procurement and queue fields

Revision ID: de987fa3527b
Revises: 2d31842ea20d
Create Date: 2026-08-29 22:59:09.910208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de987fa3527b'
down_revision: Union[str, Sequence[str], None] = '2d31842ea20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_farmers_preferred_centre', 'procurement_centres', ['preferred_centre_id'], ['id'])
        
    with op.batch_alter_table('procurement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('moisture_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exception_reason', sa.Text(), nullable=True))
        
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('FARMER', 'OPERATOR', 'ADMIN', 'PROCUREMENT_COMPANY', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('FARMER', 'OPERATOR', 'ADMIN', 'PROCUREMENT_COMPANY', name='userrole'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
               
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_column('exception_reason')
        
    with op.batch_alter_table('procurement', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('moisture_percentage')
        batch_op.drop_column('quality_grade')
        
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_farmers_preferred_centre', type_='foreignkey')
    # ### end Alembic commands ###
