"""Add lat long to ProcurementCompany

Revision ID: eb71245ae6ab
Revises: c1a9548d19c2
Create Date: 2026-08-31 00:09:07.727571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb71245ae6ab'
down_revision: Union[str, Sequence[str], None] = 'c1a9548d19c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_companies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('procurement_companies', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_companies', 'longitude')
    op.drop_column('procurement_companies', 'latitude')
    # ### end Alembic commands ###
